# Generated by Django 5.0 on 2023-12-15 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('block_content', models.JSONField(default=dict)),
                ('slag', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_image', to='common.image')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_meta', to='common.meta')),
                ('tech_and_solution', models.ManyToManyField(related_name='course_technology', to='common.technology')),
            ],
            options={
                'db_table': 'academy_course',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dt_start', models.DateTimeField()),
                ('dt_end', models.DateTimeField()),
                ('block_content', models.JSONField(default=dict)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('course', models.ManyToManyField(related_name='promotion_courses', to='academy.course')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_image', to='common.image')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_meta', to='common.meta')),
            ],
            options={
                'db_table': 'academy_promotion',
            },
        ),
    ]
