# Generated by Django 5.0 on 2023-12-15 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('block_content', models.JSONField(default=dict)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_image', to='common.image')),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='CompanyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('block_content', models.JSONField(default=dict)),
                ('slag', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('order_number', models.PositiveIntegerField(default=1)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_case_image', to='common.image')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_case_image', to='common.meta')),
                ('tech_and_solutions', models.ManyToManyField(related_name='company_case_technology', to='common.technology')),
            ],
            options={
                'db_table': 'company_case',
            },
        ),
        migrations.CreateModel(
            name='CompanyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order_number', models.PositiveIntegerField(default=1)),
                ('block_content', models.JSONField(default=dict)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_service_image', to='common.image')),
            ],
            options={
                'db_table': 'company_service',
            },
        ),
    ]
