# Generated by Django 5.0 on 2023-12-15 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('block_content', models.JSONField(default=dict)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_category_image', to='common.image')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_category_meta', to='common.meta')),
            ],
            options={
                'db_table': 'blog_category',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('block_content', models.JSONField(default=dict)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.ManyToManyField(related_name='blog_post_category', to='blog.blogcategory')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post_image', to='common.image')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post_meta', to='common.meta')),
            ],
            options={
                'db_table': 'blog_post',
            },
        ),
    ]
